name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Flutter 🚀
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.5' # Matches your local environment for Dart 3.9.2 support

      - name: Install dependencies 📦
        run: flutter pub get

      - name: Build Web 🏗️
        run: flutter build web --release --base-href "/printvox_lp/"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
